[target.armv7-unknown-linux-gnueabihf]
# Needed to build cursive
pre-build = [
    "apt-get update",
    "apt-get install -y --no-install-recommends apt-utils",
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install libncurses5-dev:armhf -y",
]

[build.env]
volumes = ["DIST=../frontend/dist"]
