[package]
name = "configuration_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
web-sys = "0.3.60"
wasm-bindgen = "0.2"
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
