name: Build release

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Install cargo dependencies
      run: cargo install cross --locked &&
        cargo install --locked trunk
    - name: Install tailwindcss
      run: cd frontend && npm install
    - name: Build for Raspberry Pi 3/4/Zero 2)
      run: make app_aarch64
    - name: Rename artifacts
      run: |
        mv app/target/aarch64-unknown-linux-gnueabihf/release/app wg-display-aarch64-unknown-linux-gnueabihf
    - uses: ncipollo/release-action@v1
      with:
          artifacts: "wg-display-aarch64-unknown-linux-gnueabihf"
          artifactErrorsFailBuild: true
